import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, readlinkSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  assertManagedFileAdoptionReceipt,
  captureLegacyEntries,
  prepareAdoptionCandidate,
  readAdoptionIndex,
  recordAdoptionAudit,
  verifyAdoptionEntry,
} from "../src/adoption";
import { syncCmd } from "../src/commands/sync";
import { loadManifest } from "../src/manifest";
import { inspectManagedFiles } from "../src/managed-files";
import { renderTargets } from "../src/render";

function manifest(repo: string): void {
  mkdirSync(join(repo, ".agents"), { recursive: true });
  writeFileSync(
    join(repo, ".agents/manifest.yaml"),
    "spec: ai-harness/v0\nidentity: { name: adoption, summary: adoption fixture }\n",
  );
}

function preparedScenario(verdict: "pass" | "fail" = "pass") {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-receipt-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-receipt-external-"));
  const candidate = join(external, "candidate");
  const report = join(external, "audit-report.json");
  writeFileSync(join(repo, "AGENTS.md"), "# Original rules\n\nPreserve this exact text.\n");
  symlinkSync("AGENTS.md", join(repo, "CLAUDE.md"));
  manifest(repo);
  captureLegacyEntries(repo);
  const metadata = prepareAdoptionCandidate(repo, candidate);
  writeFileSync(report, JSON.stringify({ verdict, notes: "independent comparison completed" }) + "\n", { mode: 0o600 });
  const recorded = recordAdoptionAudit(repo, candidate, {
    verdict,
    reason: "Compared every legacy entry with the generated candidate",
    reportPath: report,
  });
  const inspections = inspectManagedFiles(repo, renderTargets(loadManifest(repo)));
  return { repo, external, candidate, report, metadata, receipt: recorded.receiptPath, inspections };
}

test("legacy entry capture preserves bytes, hashes, and symlink topology", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-"));
  const original = "# Existing agent rules\n\nNever lose this rule.\n";
  writeFileSync(join(repo, "AGENTS.md"), original);
  symlinkSync("AGENTS.md", join(repo, "CLAUDE.md"));

  const index = captureLegacyEntries(repo);
  assert.equal(index.entries.length, 2);
  const agents = index.entries.find((entry) => entry.path === "AGENTS.md")!;
  assert.equal(agents.type, "file");
  assert.equal(agents.mode, 0o644);
  assert.ok(agents.sha256);
  assert.equal(readFileSync(join(repo, agents.snapshot!), "utf8"), original);
  const claude = index.entries.find((entry) => entry.path === "CLAUDE.md")!;
  assert.equal(claude.type, "symlink");
  assert.equal(claude.linkTarget, "AGENTS.md");
  assert.equal(lstatSync(join(repo, "CLAUDE.md")).isSymbolicLink(), true);
  assert.deepEqual(readAdoptionIndex(repo), index);
  assert.equal(verifyAdoptionEntry(repo, agents), true);
  assert.equal(verifyAdoptionEntry(repo, claude), true);
});

test("legacy evidence binds file mode and rejects mode-only drift", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-mode-"));
  const path = join(repo, "AGENTS.md");
  writeFileSync(path, "mode-sensitive rules\n", { mode: 0o644 });
  const entry = captureLegacyEntries(repo).entries.find((item) => item.path === "AGENTS.md")!;
  assert.equal(entry.mode, 0o644);
  chmodSync(path, 0o755);
  assert.equal(verifyAdoptionEntry(repo, entry), false);
  assert.throws(() => captureLegacyEntries(repo), /legacy snapshot.*不匹配/);
});

test("an adoption snapshot never authorizes a root file that changed after capture", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-stale-"));
  writeFileSync(join(repo, "AGENTS.md"), "old\n");
  const index = captureLegacyEntries(repo);
  const entry = index.entries[0];
  writeFileSync(join(repo, "AGENTS.md"), "changed after audit\n");
  assert.equal(verifyAdoptionEntry(repo, entry), false);
  assert.throws(() => captureLegacyEntries(repo), /已有 legacy snapshot.*不匹配/);
  assert.equal(readFileSync(join(repo, entry.snapshot!), "utf8"), "old\n");
});

test("capture ignores missing or already generated entry files", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-generated-"));
  writeFileSync(
    join(repo, "AGENTS.md"),
    "<!-- GENERATED by ai-harness — DO NOT EDIT. Source of truth: .agents/manifest.yaml. -->\n",
  );
  const index = captureLegacyEntries(repo);
  assert.deepEqual(index.entries, []);
});

test("sync refuses snapshot-only takeover and accepts the exact candidate plus pass receipt", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-sync-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-sync-external-"));
  writeFileSync(join(repo, "AGENTS.md"), "# Important existing rules\n");
  writeFileSync(join(repo, "CLAUDE.md"), "@AGENTS.md\n");
  manifest(repo);

  assert.throws(() => syncCmd(repo), /prepare-adoption|candidate/i);
  assert.equal(readFileSync(join(repo, "AGENTS.md"), "utf8"), "# Important existing rules\n");

  captureLegacyEntries(repo);
  assert.throws(() => syncCmd(repo, { adoptExisting: true }), /candidate|receipt/i);
  const candidate = join(external, "candidate");
  const report = join(external, "audit.json");
  prepareAdoptionCandidate(repo, candidate);
  writeFileSync(report, "{\"verdict\":\"pass\"}\n");
  const receipt = recordAdoptionAudit(repo, candidate, {
    verdict: "pass",
    reason: "Blind comparison preserved the original rule",
    reportPath: report,
  }).receiptPath;
  syncCmd(repo, { adoptExisting: true, adoptionCandidate: candidate, adoptionAudit: receipt });
  assert.match(readFileSync(join(repo, "AGENTS.md"), "utf8"), /GENERATED by ai-harness/);
  assert.equal(readFileSync(join(repo, ".agents/adoption/legacy/AGENTS.md.pre-harness"), "utf8"), "# Important existing rules\n");
});

test("merely mentioning the generated marker in prose does not grant ownership", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-marker-"));
  writeFileSync(join(repo, "AGENTS.md"), "# Existing guide\n\nThis discusses GENERATED by ai-harness behavior.\n");
  manifest(repo);
  assert.throws(() => syncCmd(repo), /prepare-adoption|candidate/i);
  assert.match(readFileSync(join(repo, "AGENTS.md"), "utf8"), /^# Existing guide/);
});

test("explicit adoption still refuses when either the source or stored snapshot changed", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-tamper-"));
  writeFileSync(join(repo, "AGENTS.md"), "original\n");
  manifest(repo);
  const index = captureLegacyEntries(repo);
  const entry = index.entries.find((item) => item.path === "AGENTS.md")!;
  writeFileSync(join(repo, entry.snapshot!), "tampered snapshot\n");

  assert.equal(verifyAdoptionEntry(repo, entry), false);
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-tamper-external-"));
  assert.throws(() => prepareAdoptionCandidate(repo, join(external, "candidate")), /legacy evidence.*stale/i);
  assert.throws(() => syncCmd(repo, { adoptExisting: true }), /candidate|receipt/i);
  assert.equal(readFileSync(join(repo, "AGENTS.md"), "utf8"), "original\n");
});

test("a tampered adoption index cannot redirect snapshot verification outside the repository", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-index-"));
  mkdirSync(join(repo, ".agents/adoption"), { recursive: true });
  writeFileSync(
    join(repo, ".agents/adoption/legacy-index.json"),
    JSON.stringify({
      schema: "ai-harness/adoption/v1",
      capturedAt: new Date().toISOString(),
      entries: [{ path: "AGENTS.md", type: "file", sha256: "deadbeef", snapshot: "../../outside" }],
    }),
  );
  assert.throws(() => readAdoptionIndex(repo), /snapshot.*安全|adoption.*格式无效/i);
});

test("legacy capture refuses a symlink adoption index without writing outside the repository", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-index-link-repo-"));
  const outside = join(mkdtempSync(join(tmpdir(), "hk-adoption-index-link-outside-")), "outside.json");
  writeFileSync(outside, "must remain unchanged\n");
  writeFileSync(join(repo, "AGENTS.md"), "legacy rule\n");
  mkdirSync(join(repo, ".agents/adoption"), { recursive: true });
  symlinkSync(outside, join(repo, ".agents/adoption/legacy-index.json"));

  assert.throws(() => captureLegacyEntries(repo), /index.*regular file.*symlink|must not be a symlink/i);
  assert.equal(readFileSync(outside, "utf8"), "must remain unchanged\n");
  assert.equal(existsSync(join(repo, ".agents/adoption/legacy/AGENTS.md.pre-harness")), false);
});

test("legacy capture refuses a symlink snapshot without overwriting its target", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-snapshot-link-repo-"));
  const outside = join(mkdtempSync(join(tmpdir(), "hk-adoption-snapshot-link-outside-")), "outside.md");
  writeFileSync(outside, "outside bytes stay\n");
  writeFileSync(join(repo, "AGENTS.md"), "legacy rule\n");
  mkdirSync(join(repo, ".agents/adoption/legacy"), { recursive: true });
  symlinkSync(outside, join(repo, ".agents/adoption/legacy/AGENTS.md.pre-harness"));

  assert.throws(() => captureLegacyEntries(repo), /snapshot.*regular file.*symlink|must not be a symlink/i);
  assert.equal(readFileSync(outside, "utf8"), "outside bytes stay\n");
  assert.equal(existsSync(join(repo, ".agents/adoption/legacy-index.json")), false);
});

test("an index race never deletes a snapshot concurrently updated through the same inode", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-index-race-repo-"));
  const snapshot = join(repo, ".agents/adoption/legacy/AGENTS.md.pre-harness");
  const index = join(repo, ".agents/adoption/legacy-index.json");
  writeFileSync(join(repo, "AGENTS.md"), "captured bytes\n");

  assert.throws(
    () => captureLegacyEntries(repo, {
      afterSnapshotsInstalled() {
        writeFileSync(snapshot, "concurrent owner\n");
        writeFileSync(index, "{}\n");
      },
    }),
    /index appeared.*snapshots retained for recovery/i,
  );
  assert.equal(readFileSync(snapshot, "utf8"), "concurrent owner\n");
  assert.equal(readFileSync(index, "utf8"), "{}\n");
});

test("prepare creates a private external audit bundle without changing live entry files", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-prepare-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-prepare-external-"));
  const output = join(external, "candidate");
  const original = "# Existing rules\n\nKeep these bytes.\n";
  writeFileSync(join(repo, "AGENTS.md"), original);
  symlinkSync("AGENTS.md", join(repo, "CLAUDE.md"));
  manifest(repo);
  captureLegacyEntries(repo);

  const metadata = prepareAdoptionCandidate(repo, output);

  assert.equal(readFileSync(join(repo, "AGENTS.md"), "utf8"), original);
  assert.equal(lstatSync(join(repo, "CLAUDE.md")).isSymbolicLink(), true);
  assert.equal(readlinkSync(join(repo, "CLAUDE.md")), "AGENTS.md");
  assert.equal(metadata.assurance, "declared");
  assert.equal(metadata.independence, "unverified");
  assert.match(metadata.candidateHash, /^[a-f0-9]{64}$/);
  assert.equal(lstatSync(output).mode & 0o777, 0o700);
  assert.equal(lstatSync(join(output, "candidate.json")).mode & 0o777, 0o600);
  assert.equal(lstatSync(join(output, "generated/AGENTS.md")).mode & 0o777, 0o600);
  assert.equal(lstatSync(join(output, "legacy/AGENTS.md.pre-harness")).mode & 0o777, 0o600);
  assert.equal(metadata.legacy.find((item) => item.path === "AGENTS.md")?.mode, 0o644);
});

test("blind-audit bundle contains every nested agent entry and recursively referenced in-repo text document", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-guidance-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-guidance-external-"));
  mkdirSync(join(repo, "packages/one"), { recursive: true });
  mkdirSync(join(repo, "odd-place/deeper"), { recursive: true });
  mkdirSync(join(repo, "another-name"), { recursive: true });
  writeFileSync(join(repo, "AGENTS.md"), "Read [the policy](odd-place/policy.md).\n");
  writeFileSync(join(repo, "packages/one/AGENTS.md"), "Also read @../../another-name/context.txt and ../../another-name/extra.md\n");
  symlinkSync("AGENTS.md", join(repo, "packages/one/CLAUDE.md"));
  writeFileSync(join(repo, "odd-place/policy.md"), "Continue with [details](deeper/details.rst).\n");
  writeFileSync(join(repo, "odd-place/deeper/details.rst"), "deep rule\n");
  writeFileSync(join(repo, "another-name/context.txt"), "nested context\n");
  writeFileSync(join(repo, "another-name/extra.md"), "extra context\n");
  manifest(repo);

  const index = captureLegacyEntries(repo);
  const expected = [
    "another-name/context.txt",
    "another-name/extra.md",
    "odd-place/deeper/details.rst",
    "odd-place/policy.md",
    "packages/one/AGENTS.md",
    "packages/one/CLAUDE.md",
  ];
  assert.deepEqual(index.entries.map((entry) => entry.path), ["AGENTS.md"]);
  assert.deepEqual(readdirSync(join(repo, ".agents/adoption/legacy")), ["AGENTS.md.pre-harness"]);

  const output = join(external, "candidate");
  const metadata = prepareAdoptionCandidate(repo, output);
  assert.deepEqual(metadata.guidance.map((entry) => entry.path), expected);
  for (const entry of metadata.guidance) {
    if (entry.type === "file") assert.deepEqual(readFileSync(join(output, entry.artifact)), readFileSync(join(repo, entry.path)));
    else assert.match(entry.artifact, /guidance\/[a-f0-9]{64}\.symlink\.json$/);
    assert.match(entry.sha256, /^[a-f0-9]{64}$/);
  }
});

test("blind-audit discovery includes gitignored nested agent entries without copying them into repository legacy evidence", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-ignored-guidance-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-ignored-guidance-external-"));
  execFileSync("git", ["init", "-q"], { cwd: repo });
  writeFileSync(join(repo, ".gitignore"), "ignored-scope/\n");
  writeFileSync(join(repo, "AGENTS.md"), "root guidance\n");
  mkdirSync(join(repo, "ignored-scope"));
  writeFileSync(join(repo, "ignored-scope/AGENTS.md"), "Read [ignored policy](policy.md).\n");
  writeFileSync(join(repo, "ignored-scope/policy.md"), "ignored but still repository guidance\n");
  manifest(repo);
  assert.match(execFileSync("git", ["check-ignore", "ignored-scope/AGENTS.md"], { cwd: repo, encoding: "utf8" }), /AGENTS\.md/);

  const index = captureLegacyEntries(repo);
  assert.deepEqual(index.entries.map((entry) => entry.path), ["AGENTS.md"]);
  assert.deepEqual(readdirSync(join(repo, ".agents/adoption/legacy")), ["AGENTS.md.pre-harness"]);

  const output = join(external, "candidate");
  const metadata = prepareAdoptionCandidate(repo, output);
  assert.deepEqual(metadata.guidance.map((entry) => entry.path), ["ignored-scope/AGENTS.md", "ignored-scope/policy.md"]);
  for (const entry of metadata.guidance) {
    assert.equal(entry.type, "file");
    assert.deepEqual(readFileSync(join(output, entry.artifact)), readFileSync(join(repo, entry.path)));
  }
  assert.deepEqual(readdirSync(join(repo, ".agents/adoption/legacy")), ["AGENTS.md.pre-harness"]);
});

test("tracked agent entries remain guidance under a pruned vendor-style directory name", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-tracked-vendor-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-tracked-vendor-external-"));
  execFileSync("git", ["init", "-q"], { cwd: repo });
  mkdirSync(join(repo, "vendor"));
  writeFileSync(join(repo, "vendor/AGENTS.md"), "tracked vendor-scope rule\n");
  execFileSync("git", ["add", "vendor/AGENTS.md"], { cwd: repo });
  writeFileSync(join(repo, ".gitignore"), "vendor/\n");
  manifest(repo);
  captureLegacyEntries(repo);

  const output = join(external, "candidate");
  const metadata = prepareAdoptionCandidate(repo, output);
  assert.deepEqual(metadata.guidance.map((entry) => entry.path), ["vendor/AGENTS.md"]);
  assert.deepEqual(readFileSync(join(output, metadata.guidance[0]!.artifact)), readFileSync(join(repo, "vendor/AGENTS.md")));
});

test("gitignored vendor guidance remains in the blind-audit inventory", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-ignored-vendor-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-ignored-vendor-external-"));
  execFileSync("git", ["init", "-q"], { cwd: repo });
  writeFileSync(join(repo, ".gitignore"), "vendor/\n");
  writeFileSync(join(repo, "AGENTS.md"), "root guidance\n");
  mkdirSync(join(repo, "vendor"));
  writeFileSync(join(repo, "vendor/AGENTS.md"), "ignored vendor rule\n");
  manifest(repo);
  captureLegacyEntries(repo);

  const metadata = prepareAdoptionCandidate(repo, join(external, "candidate"));
  assert.deepEqual(metadata.guidance.map((entry) => entry.path), ["vendor/AGENTS.md"]);
});

test("gitignored dist guidance is not dropped by a conventional build-directory name", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-ignored-dist-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-ignored-dist-external-"));
  execFileSync("git", ["init", "-q"], { cwd: repo });
  writeFileSync(join(repo, ".gitignore"), "dist/\n");
  writeFileSync(join(repo, "AGENTS.md"), "root guidance\n");
  mkdirSync(join(repo, "dist"));
  writeFileSync(join(repo, "dist/AGENTS.md"), "ignored dist rule\n");
  manifest(repo);
  captureLegacyEntries(repo);

  const metadata = prepareAdoptionCandidate(repo, join(external, "candidate"));
  assert.deepEqual(metadata.guidance.map((entry) => entry.path), ["dist/AGENTS.md"]);
});

test("non-Git repositories scan vendor-style directories for nested guidance", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-nongit-vendor-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-nongit-vendor-external-"));
  writeFileSync(join(repo, "AGENTS.md"), "root guidance\n");
  mkdirSync(join(repo, "vendor"));
  writeFileSync(join(repo, "vendor/AGENTS.md"), "non-git vendor rule\n");
  manifest(repo);
  captureLegacyEntries(repo);

  const metadata = prepareAdoptionCandidate(repo, join(external, "candidate"));
  assert.deepEqual(metadata.guidance.map((entry) => entry.path), ["vendor/AGENTS.md"]);
});

test("candidate preparation fails closed for missing, binary, or external-symlink referenced guidance", () => {
  for (const kind of ["missing", "binary", "symlink"] as const) {
    const repo = mkdtempSync(join(tmpdir(), `hk-adoption-unsafe-ref-${kind}-`));
    const external = mkdtempSync(join(tmpdir(), `hk-adoption-unsafe-ref-external-${kind}-`));
    writeFileSync(join(repo, "AGENTS.md"), "Read [required guidance](unusual/guide.md).\n");
    mkdirSync(join(repo, "unusual"));
    if (kind === "binary") writeFileSync(join(repo, "unusual/guide.md"), Buffer.from([0, 1, 2]));
    if (kind === "symlink") {
      const outside = join(external, "outside.md");
      writeFileSync(outside, "outside repository\n");
      symlinkSync(outside, join(repo, "unusual/guide.md"));
    }
    manifest(repo);
    captureLegacyEntries(repo);
    assert.throws(
      () => prepareAdoptionCandidate(repo, join(external, "candidate")),
      /cannot safely resolve referenced guidance|guidance symlink.*safe in-repo/i,
    );
  }
});

test("candidate preparation refuses a guidance file swapped to a symlink after lstat", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-guidance-race-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-guidance-race-external-"));
  mkdirSync(join(repo, "unusual"));
  writeFileSync(join(repo, "AGENTS.md"), "Read [required guidance](unusual/guide.md).\n");
  const guidance = join(repo, "unusual/guide.md");
  writeFileSync(guidance, "safe repository guidance\n");
  const outside = join(external, "outside.md");
  writeFileSync(outside, "must never enter the audit bundle\n");
  manifest(repo);
  captureLegacyEntries(repo);

  let swapped = false;
  assert.throws(
    () => prepareAdoptionCandidate(repo, join(external, "candidate"), {
      afterGuidanceFileLstat: (path) => {
        if (path !== "unusual/guide.md" || swapped) return;
        unlinkSync(guidance);
        symlinkSync(outside, guidance);
        swapped = true;
      },
    }),
    /guidance.*(?:symlink|changed)|without following links/i,
  );
  assert.equal(swapped, true, "the test must replace the file inside the lstat/open window");
  assert.equal(existsSync(join(external, "candidate")), false);
});

test("guidance discovery ignores Markdown images and ordinary code or asset links", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-nondoc-links-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-nondoc-links-external-"));
  writeFileSync(join(repo, "AGENTS.md"), "![diagram](missing.md)\n[code](src/missing.ts)\n[asset](images/missing.png)\n");
  manifest(repo);
  captureLegacyEntries(repo);
  const metadata = prepareAdoptionCandidate(repo, join(external, "candidate"));
  assert.deepEqual(metadata.guidance, []);
});

test("prepare rejects in-repository and symlink candidate destinations", () => {
  const repo = mkdtempSync(join(tmpdir(), "hk-adoption-output-repo-"));
  const external = mkdtempSync(join(tmpdir(), "hk-adoption-output-external-"));
  writeFileSync(join(repo, "AGENTS.md"), "legacy\n");
  manifest(repo);
  captureLegacyEntries(repo);

  assert.throws(() => prepareAdoptionCandidate(repo, join(repo, "audit-candidate")), /outside the repository/i);
  const link = join(external, "candidate-link");
  mkdirSync(join(external, "real-candidate"));
  symlinkSync(join(external, "real-candidate"), link);
  assert.throws(() => prepareAdoptionCandidate(repo, link), /must not be a symlink/i);
});

test("a declared pass receipt authorizes the exact same managed-file preflight", () => {
  const scenario = preparedScenario();
  assert.doesNotThrow(() =>
    assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
  );
  const receipt = JSON.parse(readFileSync(scenario.receipt, "utf8"));
  assert.equal(receipt.assurance, "declared");
  assert.equal(receipt.independence, "unverified");
  assert.equal(lstatSync(scenario.receipt).mode & 0o777, 0o600);
});

test("authorization refuses when no audit receipt exists", () => {
  const scenario = preparedScenario();
  assert.throws(
    () =>
      assertManagedFileAdoptionReceipt(
        scenario.repo,
        scenario.inspections,
        scenario.candidate,
        join(scenario.external, "missing-receipt.json"),
      ),
    /receipt|ENOENT|missing/i,
  );
});

test("authorization refuses a declared fail receipt", () => {
  const scenario = preparedScenario("fail");
  assert.throws(
    () => assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
    /verdict.*fail|pass is required/i,
  );
});

test("authorization refuses when the bound audit report changes", () => {
  const scenario = preparedScenario();
  writeFileSync(scenario.report, "{\"tampered\":true}\n");
  assert.throws(
    () => assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
    /report hash mismatch/i,
  );
});

test("authorization refuses when a generated candidate artifact changes", () => {
  const scenario = preparedScenario();
  writeFileSync(join(scenario.candidate, "generated/AGENTS.md"), "tampered candidate\n");
  assert.throws(
    () => assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
    /candidate.*hash mismatch|hash mismatch.*generated/i,
  );
});

test("authorization refuses candidate metadata that upgrades its declared assurance", () => {
  const scenario = preparedScenario();
  const metadataPath = join(scenario.candidate, "candidate.json");
  const metadata = JSON.parse(readFileSync(metadataPath, "utf8"));
  metadata.independence = "verified";
  writeFileSync(metadataPath, JSON.stringify(metadata) + "\n");
  assert.throws(
    () => assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
    /candidate.json.*invalid|hash mismatch/i,
  );
});

test("authorization refuses when the manifest renders different targets or bytes", () => {
  const scenario = preparedScenario();
  writeFileSync(
    join(scenario.repo, ".agents/manifest.yaml"),
    "spec: ai-harness/v0\nidentity: { name: adoption, summary: changed after audit }\n",
  );
  assert.throws(
    () => assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
    /manifest changed|render differs/i,
  );
});

test("authorization refuses when live legacy bytes or mode change after audit", () => {
  for (const drift of ["bytes", "mode"] as const) {
    const scenario = preparedScenario();
    const agents = join(scenario.repo, "AGENTS.md");
    if (drift === "bytes") writeFileSync(agents, "changed after candidate audit\n");
    else chmodSync(agents, 0o755);
    assert.throws(
      () => assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
      /legacy snapshot.*stale|legacy.*changed/i,
    );
  }
});

test("authorization revalidates referenced guidance bytes and mode at apply time", () => {
  for (const drift of ["bytes", "mode"] as const) {
    const repo = mkdtempSync(join(tmpdir(), `hk-adoption-reference-drift-${drift}-`));
    const external = mkdtempSync(join(tmpdir(), `hk-adoption-reference-drift-external-${drift}-`));
    mkdirSync(join(repo, "unusual"));
    writeFileSync(join(repo, "AGENTS.md"), "Read [policy](unusual/review.md).\n");
    const reference = join(repo, "unusual/review.md");
    writeFileSync(reference, "preserve this rule\n", { mode: 0o644 });
    manifest(repo);
    captureLegacyEntries(repo);
    const candidate = join(external, "candidate");
    prepareAdoptionCandidate(repo, candidate);
    const report = join(external, "report.json");
    writeFileSync(report, "{\"verdict\":\"pass\"}\n");
    const receipt = recordAdoptionAudit(repo, candidate, {
      verdict: "pass",
      reason: "blind audit complete",
      reportPath: report,
    }).receiptPath;
    const inspections = inspectManagedFiles(repo, renderTargets(loadManifest(repo)));

    if (drift === "bytes") writeFileSync(reference, "changed after audit\n");
    else chmodSync(reference, 0o755);
    assert.throws(
      () => assertManagedFileAdoptionReceipt(repo, inspections, candidate, receipt),
      /guidance.*changed/i,
    );
  }
});

test("authorization refuses when the live legacy index changes after audit", () => {
  const scenario = preparedScenario();
  const indexPath = join(scenario.repo, ".agents/adoption/legacy-index.json");
  const index = JSON.parse(readFileSync(indexPath, "utf8"));
  index.capturedAt = "2099-01-01T00:00:00.000Z";
  writeFileSync(indexPath, JSON.stringify(index, null, 2) + "\n");
  assert.throws(
    () => assertManagedFileAdoptionReceipt(scenario.repo, scenario.inspections, scenario.candidate, scenario.receipt),
    /index changed/i,
  );
});
