import { test } from "node:test";
import assert from "node:assert/strict";
import { renderAgentsMd, renderTargets } from "../src/render";
import type { Manifest } from "../src/manifest";

const base: Manifest = {
  spec: "ai-harness/v0",
  identity: { name: "demo", summary: "a demo project" },
  capabilities: { test: { run: "pnpm test" } },
};

test("AGENTS.md carries the GEN header, the working agreement and commands", () => {
  const md = renderAgentsMd(base);
  assert.match(md, /GENERATED by ai-harness/);
  assert.match(md, /Working agreement/);
  assert.match(md, /Task Brief/);
  assert.match(md, /pnpm test/);
});

test("renderTargets omits routing/modules when absent and adds them when present", () => {
  const bare = renderTargets(base).map((t) => t[0]);
  assert.ok(bare.includes("AGENTS.md"));
  assert.ok(bare.includes("CLAUDE.md"));
  assert.ok(!bare.some((p) => p.includes(".cursor")));
  assert.ok(!bare.includes(".agents/routing.md"));
  assert.ok(!bare.includes(".agents/modules.md"));

  const rich = renderTargets({
    ...base,
    routing: [{ when: "fix a bug", read: ["src/a.ts"] }],
    modules: [{ name: "m", role: "r", entry: ["src/a.ts"] }],
  }).map((t) => t[0]);
  assert.ok(rich.includes(".agents/routing.md"));
  assert.ok(rich.includes(".agents/modules.md"));
});

test("routing step in AGENTS.md adapts to whether routing exists", () => {
  assert.match(renderAgentsMd(base), /Read the relevant files before editing/);
  assert.match(
    renderAgentsMd({ ...base, routing: [{ when: "fix" }] }),
    /routing\.md/,
  );
});

test("modules.md renders the impact-map fields (owns/tests/checks/policy/playbook)", () => {
  const targets = renderTargets({
    ...base,
    modules: [
      {
        name: "api",
        role: "r",
        entry: ["src/api/index.ts"],
        owns: ["src/api/**"],
        tests: ["test/api/**"],
        checks: ["test"],
        test_touch: "required",
        playbook: "verify-api.md",
      },
    ],
  });
  const modulesMd = targets.find((t) => t[0] === ".agents/modules.md")![1];
  assert.match(modulesMd, /Owns \(prod\):.*src\/api/);
  assert.match(modulesMd, /Tests:.*test\/api/);
  assert.match(modulesMd, /Checks:.*test/);
  assert.match(modulesMd, /Test touch:.*required/);
  assert.match(modulesMd, /Playbook:.*verify-api\.md/);
});

test("AGENTS.md points to run-checks + check-loop only when an impact map exists", () => {
  const withoutMap = renderAgentsMd(base);
  assert.doesNotMatch(withoutMap, /run-checks/);

  const withMap = renderAgentsMd({
    ...base,
    modules: [{ name: "api", role: "r", entry: ["src/a.ts"], owns: ["src/api/**"], checks: ["test"] }],
  });
  assert.match(withMap, /run-checks/);
  assert.match(withMap, /check-loop/);
});
