import { test } from "node:test";
import assert from "node:assert/strict";
import { renderAgentsMd, renderTargets } from "../src/render";
import type { Manifest } from "../src/manifest";

const base: Manifest = {
  spec: "ai-harness/v0",
  identity: { name: "demo", summary: "a demo project" },
  capabilities: { test: { run: "pnpm test" } },
};

test("AGENTS.md carries the GEN header, the working agreement and commands", () => {
  const md = renderAgentsMd(base);
  assert.match(md, /GENERATED by ai-harness/);
  assert.match(md, /Working agreement/);
  assert.match(md, /Task Brief/);
  assert.match(md, /pnpm test/);
});

test("renderTargets omits routing/modules when absent and adds them when present", () => {
  const bare = renderTargets(base).map((t) => t[0]);
  assert.ok(bare.includes("AGENTS.md"));
  assert.ok(bare.includes("CLAUDE.md"));
  assert.ok(!bare.some((p) => p.includes(".cursor")));
  assert.ok(!bare.includes(".agents/routing.md"));
  assert.ok(!bare.includes(".agents/modules.md"));

  const rich = renderTargets({
    ...base,
    routing: [{ when: "fix a bug", read: ["src/a.ts"] }],
    modules: [{ name: "m", role: "r", entry: ["src/a.ts"] }],
  }).map((t) => t[0]);
  assert.ok(rich.includes(".agents/routing.md"));
  assert.ok(rich.includes(".agents/modules.md"));
});

test("routing step in AGENTS.md adapts to whether routing exists", () => {
  assert.match(renderAgentsMd(base), /Read the relevant files before editing/);
  assert.match(
    renderAgentsMd({ ...base, routing: [{ when: "fix" }] }),
    /routing\.md/,
  );
});
