import { chmodSync, existsSync, lstatSync } from "node:fs";
import { join } from "node:path";
import pkg from "../../package.json";
import { gitRoot } from "../git";
import { err, info, ok, readText, warn, writeText } from "../util";

export type AgentTool = "claude" | "cursor" | "codex";
export const ALL_AGENTS: AgentTool[] = ["claude", "cursor", "codex"];

const SCRIPT_REL = ".agents/hooks/harness-agent-hook.sh";
const MARKER = "harness-agent-hook.sh";
const SCRIPT_MARK = "harness-kit-managed-hook (agent-lifecycle)";

function hookCommand(agent: AgentTool, event: "session-start" | "stop"): string {
  const run = `bash "$(git rev-parse --show-toplevel)/${SCRIPT_REL}" ${agent} ${event}`;
  const message = "harness-kit hook runner is missing or failed; run harness-kit run-checks and harness-kit verify manually";
  if (event === "stop") {
    const output =
      agent === "cursor"
        ? `{"followup_message":"${message}"}`
        : `{"decision":"block","reason":"${message}"}`;
    return `${run} || printf '%s\\n' '${output}'`;
  }
  return `${run} || { echo '${message}' >&2; exit 2; }`;
}

function runnerScript(): string {
  return `#!/bin/sh
# ${SCRIPT_MARK}
# Generated by harness-kit install-hooks. Re-run install-hooks to update it.
AGENT="$1"
EVENT="$2"

block_infrastructure_failure() {
  message="harness-kit hook infrastructure failed; run harness-kit run-checks and harness-kit verify manually"
  if [ "$EVENT" = "stop" ]; then
    if [ "$AGENT" = "cursor" ]; then
      printf '{"followup_message":"%s"}\n' "$message"
    else
      printf '{"decision":"block","reason":"%s"}\n' "$message"
    fi
    exit 0
  fi
  echo "$message" >&2
  exit 2
}

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || block_infrastructure_failure
cd "$ROOT" || block_infrastructure_failure
[ -f .agents/manifest.yaml ] || block_infrastructure_failure

HK="\${HARNESS_KIT_CMD:-npx -y @erzhe/harness-kit@${pkg.version}}"
output=$($HK hook-event --repo "$ROOT" --agent "$AGENT" --event "$EVENT")
code=$?
[ "$code" -eq 0 ] || block_infrastructure_failure
[ -n "$output" ] && printf '%s\n' "$output"
exit 0
`;
}

function readJson(abs: string): Record<string, unknown> | null {
  const raw = readText(abs);
  if (raw == null) return {};
  try {
    const value = JSON.parse(raw);
    return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

function writeJson(abs: string, value: unknown): void {
  writeText(abs, JSON.stringify(value, null, 2) + "\n");
}

function isManagedHook(hook: unknown): boolean {
  return typeof (hook as { command?: unknown })?.command === "string" && (hook as { command: string }).command.includes(MARKER);
}

function withoutManagedGroupHooks(groups: unknown[]): unknown[] {
  const result: unknown[] = [];
  for (const group of groups) {
    if (!group || typeof group !== "object" || Array.isArray(group)) {
      result.push(group);
      continue;
    }
    const hooks = (group as { hooks?: unknown }).hooks;
    if (!Array.isArray(hooks) || !hooks.some(isManagedHook)) {
      result.push(group);
      continue;
    }
    const remaining = hooks.filter((hook) => !isManagedHook(hook));
    if (remaining.length) result.push({ ...(group as Record<string, unknown>), hooks: remaining });
  }
  return result;
}

function installGroupStyle(repo: string, rel: string, tool: AgentTool): boolean {
  const path = join(repo, rel);
  const json = readJson(path);
  if (json == null) {
    err(`${tool}: ${rel} exists but is not valid JSON — no hooks installed`);
    return false;
  }
  const hooks = json.hooks && typeof json.hooks === "object" && !Array.isArray(json.hooks) ? (json.hooks as Record<string, unknown>) : {};
  for (const [event, command] of [
    ["SessionStart", hookCommand(tool, "session-start")],
    ["Stop", hookCommand(tool, "stop")],
  ] as const) {
    const existing = Array.isArray(hooks[event]) ? (hooks[event] as unknown[]) : [];
    hooks[event] = [...withoutManagedGroupHooks(existing), { hooks: [{ type: "command", command, timeout: 600 }] }];
  }
  json.hooks = hooks;
  writeJson(path, json);
  ok(`${tool}: installed SessionStart + Stop hooks -> ${rel}`);
  return true;
}

function cursorHasOurs(hook: unknown): boolean {
  return typeof (hook as { command?: unknown })?.command === "string" && (hook as { command: string }).command.includes(MARKER);
}

function installCursor(repo: string): boolean {
  const rel = ".cursor/hooks.json";
  const path = join(repo, rel);
  const json = readJson(path);
  if (json == null) {
    err(`cursor: ${rel} exists but is not valid JSON — no hooks installed`);
    return false;
  }
  if (json.version == null) json.version = 1;
  const hooks = json.hooks && typeof json.hooks === "object" && !Array.isArray(json.hooks) ? (json.hooks as Record<string, unknown>) : {};
  const sessionStart = Array.isArray(hooks.sessionStart) ? (hooks.sessionStart as unknown[]) : [];
  const stop = Array.isArray(hooks.stop) ? (hooks.stop as unknown[]) : [];
  hooks.sessionStart = [
    ...sessionStart.filter((hook) => !cursorHasOurs(hook)),
    { command: hookCommand("cursor", "session-start"), timeout: 600 },
  ];
  hooks.stop = [...stop.filter((hook) => !cursorHasOurs(hook)), { command: hookCommand("cursor", "stop"), timeout: 600, loop_limit: 8 }];
  json.hooks = hooks;
  writeJson(path, json);
  ok(`cursor: installed sessionStart + stop hooks -> ${rel}`);
  return true;
}

function enableCodexHooks(repo: string): boolean {
  const rel = ".codex/config.toml";
  const path = join(repo, rel);
  const raw = readText(path) ?? "";
  const lines = raw ? raw.replace(/\n$/, "").split("\n") : [];
  let featuresStart = -1;
  let featuresEnd = lines.length;
  for (let index = 0; index < lines.length; index++) {
    if (/^\s*\[features\]\s*(?:#.*)?$/.test(lines[index]!)) {
      featuresStart = index;
      continue;
    }
    if (featuresStart >= 0 && /^\s*\[.+\]\s*(?:#.*)?$/.test(lines[index]!)) {
      featuresEnd = index;
      break;
    }
  }

  if (featuresStart < 0) {
    if (lines.length && lines.at(-1) !== "") lines.push("");
    lines.push("[features]", "# harness-kit: required for project lifecycle hooks", "hooks = true");
  } else {
    const featureKeys: number[] = [];
    for (let index = featuresStart + 1; index < featuresEnd; index++) {
      if (/^\s*(?:hooks|codex_hooks)\s*=/.test(lines[index]!)) featureKeys.push(index);
    }
    if (featureKeys.length) {
      const first = featureKeys[0]!;
      const indent = lines[first]!.match(/^\s*/)?.[0] ?? "";
      lines[first] = `${indent}hooks = true`;
      for (const duplicate of featureKeys.slice(1).reverse()) lines.splice(duplicate, 1);
    } else {
      lines.splice(featuresStart + 1, 0, "# harness-kit: required for project lifecycle hooks", "hooks = true");
    }
  }
  writeText(path, lines.join("\n") + "\n");
  ok(`codex: enabled project hooks -> ${rel}`);
  return true;
}

function isLinkedWorktree(repo: string): boolean {
  try {
    return lstatSync(join(repo, ".git")).isFile();
  } catch {
    return false;
  }
}

function installRunner(repo: string, force: boolean): boolean {
  const path = join(repo, SCRIPT_REL);
  const current = readText(path);
  if (current !== null && !current.includes(SCRIPT_MARK) && !force) {
    err(`${SCRIPT_REL} exists and is not harness-kit-managed — skipped (use --force to replace)`);
    return false;
  }
  writeText(path, runnerScript());
  chmodSync(path, 0o755);
  ok(`${current === null ? "installed" : "updated"} agent hook runner -> ${SCRIPT_REL}`);
  return true;
}

export function installStopHooks(repo: string, agents: AgentTool[], force: boolean): number {
  if (!agents.length || agents.some((agent) => !ALL_AGENTS.includes(agent))) {
    err(`invalid --agents value; supported: ${ALL_AGENTS.join(",")}`);
    return 1;
  }
  try {
    repo = gitRoot(repo);
  } catch (error) {
    err(`agent hooks require a Git worktree: ${(error as Error).message}`);
    return 1;
  }
  if (!existsSync(join(repo, ".agents", "manifest.yaml"))) {
    err("agent hooks require .agents/manifest.yaml — onboard the repository first");
    return 1;
  }
  if (!installRunner(repo, force)) return 1;

  let failures = 0;
  for (const agent of agents) {
    const installed =
      agent === "cursor"
        ? installCursor(repo)
        : agent === "codex"
          ? enableCodexHooks(repo) && installGroupStyle(repo, ".codex/hooks.json", agent)
          : installGroupStyle(repo, ".claude/settings.json", agent);
    if (!installed) failures++;
  }

  if (agents.includes("codex")) {
    warn("codex: run `/hooks` to review and trust the new project hooks before they can run");
    if (isLinkedWorktree(repo))
      warn("codex: current Codex CLI versions may ignore project hooks in linked worktrees; confirm with `harness-kit evidence` after the first session");
  }
  info("\nSessionStart records the exact task base; every Stop reruns run-checks + verify.");
  info("After the first real agent session, run `harness-kit evidence`; no record means that client surface did not execute project hooks.");
  info(`Runner is pinned to @erzhe/harness-kit@${pkg.version}; override with HARNESS_KIT_CMD for local development.`);
  return failures ? 1 : 0;
}
