import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import {
  chmodSync,
  closeSync,
  constants,
  fchmodSync,
  existsSync,
  fstatSync,
  linkSync,
  lstatSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  realpathSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, extname, isAbsolute, join, normalize, relative, resolve, sep } from "node:path";
import { loadManifest, MANIFEST_REL, validateManifest } from "./manifest";
import { writeManagedFiles, type ManagedFileInspection } from "./managed-files";
import { renderTargets } from "./render";
import { sha256 } from "./util";

const INDEX_REL = ".agents/adoption/legacy-index.json";
const LEGACY_DIR_REL = ".agents/adoption/legacy";
const MANAGED_ENTRY_PATHS = ["AGENTS.md", "CLAUDE.md", ".agents/routing.md", ".agents/modules.md", ".agents/reference.md"];
const AGENT_ENTRY_NAMES = new Set(["AGENTS.md", "CLAUDE.md"]);
const DOCUMENT_EXTENSIONS = new Set([".md", ".mdx", ".markdown", ".txt", ".rst", ".adoc", ".asciidoc", ".org"]);
const ALWAYS_PRUNED_DIRECTORY_NAMES = new Set([".git", ".hg", ".svn"]);
const GENERATED_MARKER = "<!-- GENERATED by ai-harness — DO NOT EDIT.";
const CANDIDATE_METADATA = "candidate.json";
const RECEIPT_DEFAULT = "adoption-audit-receipt.json";

export const ADOPTION_CANDIDATE_SCHEMA = "ai-harness/adoption-candidate/v1" as const;
export const ADOPTION_RECEIPT_SCHEMA = "ai-harness/adoption-audit-receipt/v1" as const;

export interface AdoptionEntry {
  path: string;
  type: "file" | "symlink";
  mode?: number;
  sha256?: string;
  snapshot?: string;
  linkTarget?: string;
}

export interface AdoptionIndex {
  schema: "ai-harness/adoption/v1";
  capturedAt: string;
  entries: AdoptionEntry[];
}

export interface AdoptionCandidateLegacyEvidence {
  path: string;
  type: "file" | "symlink";
  artifact: string;
  sha256: string;
  mode?: number;
  sourceSha256?: string;
  linkTarget?: string;
}

export interface AdoptionCandidateGuidanceEvidence {
  path: string;
  type: "file" | "symlink";
  artifact: string;
  sha256: string;
  mode: number;
  linkTarget?: string;
}

export interface AdoptionCandidateTarget {
  path: string;
  artifact: string;
  sha256: string;
}

export interface AdoptionCandidateMetadata {
  schema: typeof ADOPTION_CANDIDATE_SCHEMA;
  assurance: "declared";
  independence: "unverified";
  source: {
    manifest: { path: typeof MANIFEST_REL; artifact: string; sha256: string };
    legacyIndex: { path: typeof INDEX_REL; artifact: string; sha256: string };
  };
  legacy: AdoptionCandidateLegacyEvidence[];
  guidance: AdoptionCandidateGuidanceEvidence[];
  targets: AdoptionCandidateTarget[];
  candidateHash: string;
}

export interface AdoptionAuditReceipt {
  schema: typeof ADOPTION_RECEIPT_SCHEMA;
  candidateHash: string;
  candidatePath: string;
  verdict: "pass" | "fail";
  reason: string;
  report: { path: string; sha256: string };
  recordedAt: string;
  assurance: "declared";
  independence: "unverified";
}

export interface RecordAdoptionAuditOptions {
  verdict: "pass" | "fail";
  reason: string;
  reportPath: string;
  receiptPath?: string;
}

export interface RecordedAdoptionAudit {
  receipt: AdoptionAuditReceipt;
  receiptPath: string;
}

function permissionMode(mode: number): number {
  return mode & 0o7777;
}

function validPermissionMode(mode: unknown): mode is number {
  return Number.isInteger(mode) && (mode as number) >= 0 && (mode as number) <= 0o7777;
}

function safeEvidencePath(path: string): boolean {
  try {
    return safeRelativePath(path, "legacy evidence") === path && !path.startsWith(`${LEGACY_DIR_REL}${sep}`);
  } catch {
    return false;
  }
}

function isErrno(error: unknown, code: string): boolean {
  return (error as NodeJS.ErrnoException | undefined)?.code === code;
}

function ensureNoSymlinkDirectoryChain(root: string, directory: string, label: string, create: boolean): boolean {
  if (!inside(root, directory)) throw new Error(`${label} parent escapes the repository`);
  const rel = relative(root, directory);
  let cursor = root;
  for (const component of rel.split(sep).filter(Boolean)) {
    cursor = join(cursor, component);
    let stat;
    try {
      stat = lstatSync(cursor);
    } catch (error) {
      if (!isErrno(error, "ENOENT")) throw new Error(`cannot inspect ${label} parent ${cursor}: ${errorMessage(error)}`);
      if (!create) return false;
      try {
        mkdirSync(cursor);
      } catch (mkdirError) {
        if (!isErrno(mkdirError, "EEXIST"))
          throw new Error(`cannot create ${label} parent ${cursor}: ${errorMessage(mkdirError)}`);
      }
      stat = lstatSync(cursor);
    }
    if (stat.isSymbolicLink()) throw new Error(`${label} parent must not be a symlink: ${cursor}`);
    if (!stat.isDirectory()) throw new Error(`${label} parent must be a directory: ${cursor}`);
    const resolved = realpathSync(cursor);
    if (!inside(root, resolved)) throw new Error(`${label} parent resolves outside the repository: ${cursor}`);
  }
  return true;
}

interface NoFollowFile {
  bytes: Buffer;
  mode: number;
  dev: number;
  ino: number;
}

function readOptionalRepositoryFile(repoRoot: string, relativePath: string, label: string): NoFollowFile | null {
  const normalized = safeRelativePath(relativePath, label);
  const absolute = resolve(repoRoot, normalized);
  if (!inside(repoRoot, absolute) || absolute === repoRoot) throw new Error(`${label} path escapes the repository`);
  if (!ensureNoSymlinkDirectoryChain(repoRoot, dirname(absolute), label, false)) return null;
  let before;
  try {
    before = lstatSync(absolute);
  } catch (error) {
    if (isErrno(error, "ENOENT")) return null;
    throw new Error(`cannot inspect ${label}: ${errorMessage(error)}`);
  }
  if (before.isSymbolicLink() || !before.isFile()) throw new Error(`${label} must be a regular file, not a symlink: ${relativePath}`);
  let fd: number;
  try {
    fd = openSync(absolute, constants.O_RDONLY | constants.O_NOFOLLOW);
  } catch (error) {
    throw new Error(`cannot open ${label} without following links: ${errorMessage(error)}`);
  }
  try {
    const opened = fstatSync(fd);
    if (!opened.isFile() || opened.dev !== before.dev || opened.ino !== before.ino)
      throw new Error(`${label} changed while it was being inspected: ${relativePath}`);
    return {
      bytes: readFileSync(fd),
      mode: permissionMode(opened.mode),
      dev: opened.dev,
      ino: opened.ino,
    };
  } finally {
    closeSync(fd);
  }
}

function parseAdoptionIndex(raw: string): AdoptionIndex {
  let value: Partial<AdoptionIndex>;
  try {
    value = JSON.parse(raw) as Partial<AdoptionIndex>;
  } catch (error) {
    throw new Error(`${INDEX_REL} 格式无效：${errorMessage(error)}`);
  }
  if (value.schema !== "ai-harness/adoption/v1" || typeof value.capturedAt !== "string" || !Array.isArray(value.entries))
    throw new Error(`${INDEX_REL} 格式无效`);
  const seen = new Set<string>();
  for (const entry of value.entries as AdoptionEntry[]) {
    if (!entry || typeof entry !== "object" || !MANAGED_ENTRY_PATHS.includes(entry.path) || seen.has(entry.path))
      throw new Error(`${INDEX_REL} 格式无效：entry path 不安全或重复`);
    seen.add(entry.path);
    if (entry.type === "file") {
      const expectedSnapshot = join(LEGACY_DIR_REL, snapshotName(entry.path));
      if (!/^[a-f0-9]{64}$/.test(entry.sha256 ?? "") || entry.snapshot !== expectedSnapshot || !validPermissionMode(entry.mode))
        throw new Error(`${INDEX_REL} 格式无效：${entry.path} snapshot/mode/hash 无效`);
    } else if (entry.type === "symlink") {
      if (typeof entry.linkTarget !== "string") throw new Error(`${INDEX_REL} 格式无效：${entry.path} symlink target 无效`);
    } else throw new Error(`${INDEX_REL} 格式无效：${entry.path} type 无效`);
  }
  return value as AdoptionIndex;
}

function readAdoptionIndexSource(repo: string): { index: AdoptionIndex | null; raw: string | null } {
  const root = repositoryRoot(repo);
  const source = readOptionalRepositoryFile(root, INDEX_REL, "legacy adoption index");
  if (!source) return { index: null, raw: null };
  const raw = source.bytes.toString("utf8");
  return { index: parseAdoptionIndex(raw), raw };
}

export function readAdoptionIndex(repo: string): AdoptionIndex | null {
  return readAdoptionIndexSource(repo).index;
}

export function verifyAdoptionEntry(repo: string, entry: AdoptionEntry): boolean {
  const root = repositoryRoot(repo);
  const path = join(root, entry.path);
  let stat;
  try {
    if (!ensureNoSymlinkDirectoryChain(root, dirname(path), `legacy source ${entry.path}`, false)) return false;
    stat = lstatSync(path);
  } catch {
    return false;
  }
  if (entry.type === "symlink") return stat.isSymbolicLink() && readlinkSync(path) === entry.linkTarget;
  if (!stat.isFile() || stat.isSymbolicLink() || !entry.sha256 || !entry.snapshot || !validPermissionMode(entry.mode)) return false;
  try {
    const source = readOptionalRepositoryFile(root, entry.path, `legacy source ${entry.path}`);
    const snapshot = readOptionalRepositoryFile(root, entry.snapshot, `legacy snapshot ${entry.path}`);
    return !!source && !!snapshot && source.mode === entry.mode && snapshot.mode === entry.mode &&
      sha256(source.bytes) === entry.sha256 && sha256(snapshot.bytes) === entry.sha256;
  } catch {
    return false;
  }
}

function snapshotName(path: string): string {
  return path.replaceAll("/", "__") + ".pre-harness";
}

interface PendingSnapshot {
  relativePath: string;
  bytes: Buffer;
  mode: number;
}

interface CapturedEntry {
  entry: AdoptionEntry | null;
  pendingSnapshot?: PendingSnapshot;
}

function captureEntry(repo: string, path: string): CapturedEntry {
  const absolute = join(repo, path);
  let stat;
  try {
    stat = lstatSync(absolute);
  } catch (error) {
    if (isErrno(error, "ENOENT")) return { entry: null };
    throw error;
  }
  if (stat.isSymbolicLink()) return { entry: { path, type: "symlink", linkTarget: readlinkSync(absolute) } };
  if (!stat.isFile()) throw new Error(`无法接管 ${path}：它既不是普通文件也不是软链接`);
  const source = readOptionalRepositoryFile(repo, path, `legacy source ${path}`);
  if (!source) return { entry: null };
  const content = source.bytes;
  if (content.toString("utf8").startsWith(GENERATED_MARKER)) return { entry: null };
  const mode = source.mode;
  const snapshot = join(LEGACY_DIR_REL, snapshotName(path));
  const existing = readOptionalRepositoryFile(repo, snapshot, `legacy snapshot ${path}`);
  if (existing && (sha256(existing.bytes) !== sha256(content) || existing.mode !== mode))
    throw new Error(`已有 legacy snapshot 内容或 mode 不匹配，拒绝覆盖: ${snapshot}`);
  return {
    entry: { path, type: "file", mode, sha256: sha256(content), snapshot },
    ...(existing ? {} : { pendingSnapshot: { relativePath: snapshot, bytes: content, mode } }),
  };
}

function findAgentEntryPaths(repo: string): string[] {
  const entries = new Set<string>();

  // The Git inventory is a cheap first pass. The filesystem walk remains
  // authoritative because a repository may intentionally keep agent guidance
  // under any ignored or unconventional directory name.
  try {
    const tracked = execFileSync("git", ["ls-files", "--cached", "-z"], {
      cwd: repo,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      maxBuffer: 32 * 1024 * 1024,
    });
    for (const path of tracked.split("\0").filter(Boolean)) {
      const normalized = normalize(path);
      if (
        AGENT_ENTRY_NAMES.has(basename(normalized)) &&
        safeEvidencePath(normalized) &&
        !normalized.startsWith(`.agents${sep}adoption${sep}`) &&
        entryExists(join(repo, normalized))
      ) entries.add(normalized);
    }
  } catch {
    // Non-Git repositories are still covered by the safe filesystem walk.
  }

  const walk = (directory: string, prefix: string): void => {
    const directoryStat = lstatSync(directory);
    if (directoryStat.isSymbolicLink() || !directoryStat.isDirectory() || !inside(repo, realpathSync(directory)))
      throw new Error(`guidance scan directory is unsafe or outside the repository: ${directory}`);
    for (const item of readdirSync(directory, { withFileTypes: true })) {
      const path = prefix ? join(prefix, item.name) : item.name;
      const absolute = join(directory, item.name);
      const stat = lstatSync(absolute);
      if (stat.isSymbolicLink()) {
        if (AGENT_ENTRY_NAMES.has(item.name)) entries.add(path);
        continue;
      }
      if (stat.isDirectory()) {
        const adoptionEvidence = item.name === "adoption" && basename(prefix) === ".agents";
        if (
          ALWAYS_PRUNED_DIRECTORY_NAMES.has(item.name) ||
          adoptionEvidence
        ) continue;
        walk(absolute, path);
        continue;
      }
      if (stat.isFile() && AGENT_ENTRY_NAMES.has(item.name)) entries.add(path);
    }
  };
  walk(repo, "");
  return [...entries].sort();
}

interface InstalledSnapshot {
  absolutePath: string;
}

function retainedSnapshotNotice(installed: readonly InstalledSnapshot[]): string {
  if (!installed.length) return "";
  // Snapshot capture is append-only evidence. If the index transaction fails,
  // deleting a just-installed path is unsafe: another writer may have updated
  // the same inode after our last observation. Retaining the no-replace
  // snapshot is recoverable and cannot overwrite a live entry file.
  return `; new snapshots retained for recovery: ${installed.map((item) => item.absolutePath).join(", ")}`;
}

function installPendingSnapshots(repoRoot: string, pending: readonly PendingSnapshot[]): InstalledSnapshot[] {
  const installed: InstalledSnapshot[] = [];
  let tempPath: string | null = null;
  try {
    for (const snapshot of pending) {
      const absolute = resolve(repoRoot, snapshot.relativePath);
      ensureNoSymlinkDirectoryChain(repoRoot, dirname(absolute), `legacy snapshot ${snapshot.relativePath}`, true);
      tempPath = join(
        dirname(absolute),
        `.${basename(absolute)}.harness-kit-adoption-${process.pid}-${randomUUID()}.tmp`,
      );
      const fd = openSync(
        tempPath,
        constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW,
        snapshot.mode & 0o777,
      );
      try {
        writeFileSync(fd, snapshot.bytes);
        fchmodSync(fd, snapshot.mode);
        const stat = fstatSync(fd);
        if (!stat.isFile()) throw new Error(`staged legacy snapshot is not a regular file: ${snapshot.relativePath}`);
      } finally {
        closeSync(fd);
      }
      linkSync(tempPath, absolute);
      installed.push({ absolutePath: absolute });
      unlinkSync(tempPath);
      tempPath = null;
    }
    return installed;
  } catch (error) {
    if (tempPath) {
      try {
        unlinkSync(tempPath);
      } catch (cleanupError) {
        if (!isErrno(cleanupError, "ENOENT")) {
          // The primary failure and installed-snapshot rollback are more useful.
        }
      }
    }
    throw new Error(`${errorMessage(error)}${retainedSnapshotNotice(installed)}`);
  }
}

function entryExists(path: string): boolean {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}

function textCanContainReferences(bytes: Buffer): boolean {
  return !bytes.includes(0);
}

function isLegacyEntry(path: string): boolean {
  const stat = lstatSync(path);
  if (stat.isSymbolicLink() || !stat.isFile()) return true;
  return !readFileSync(path).toString("utf8").startsWith(GENERATED_MARKER);
}

interface LiveGuidanceEvidence {
  path: string;
  type: "file" | "symlink";
  mode: number;
  bytes?: Buffer;
  linkTarget?: string;
}

function documentLike(path: string): boolean {
  return AGENT_ENTRY_NAMES.has(basename(path)) || DOCUMENT_EXTENSIONS.has(extname(path).toLowerCase());
}

function cleanReference(raw: string): string | null {
  let value = raw.trim();
  if (value.startsWith("<") && value.endsWith(">")) value = value.slice(1, -1).trim();
  else value = value.split(/\s+/)[0] ?? "";
  if (!value || value.startsWith("#") || value.startsWith("//") || /^[a-z][a-z0-9+.-]*:/i.test(value)) return null;
  value = value.replace(/[?#].*$/, "");
  try {
    value = decodeURIComponent(value);
  } catch {
    return null;
  }
  return value || null;
}

function explicitReferences(content: string): string[] {
  const references = new Set<string>();
  for (const match of content.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) {
    if ((match.index ?? 0) > 0 && content[(match.index ?? 0) - 1] === "!") continue;
    const path = cleanReference(match[1] ?? "");
    if (path && documentLike(path)) references.add(path);
  }
  const prose = content.replace(/!?\[[^\]]*\]\([^)]+\)/g, "");
  for (const match of prose.matchAll(/(?:^|[\s(`'\"])(?:@)([A-Za-z0-9._/\\%-]+)/gm)) {
    const path = cleanReference(match[1] ?? "");
    if (path && documentLike(path)) references.add(path);
  }
  for (const match of prose.matchAll(/(?:^|[\s`'\"(])((?:(?:\.{1,2})\/)*[A-Za-z0-9._%-]+(?:\/[A-Za-z0-9._%-]+)*\.(?:md|mdx|markdown|txt|rst|adoc|asciidoc|org))(?=$|[\s`'\"),:;])/gim)) {
    const path = cleanReference(match[1] ?? "");
    if (path) references.add(path);
  }
  return [...references];
}

function resolveGuidanceReference(repoRoot: string, sourcePath: string, reference: string): string | null {
  const candidates = reference.startsWith("/")
    ? [resolve(repoRoot, reference.slice(1))]
    : [resolve(repoRoot, dirname(sourcePath), reference), resolve(repoRoot, reference)];
  for (const absolute of candidates) {
    if (!inside(repoRoot, absolute) || !entryExists(absolute)) continue;
    let stat;
    try {
      const parent = realpathSync(dirname(absolute));
      if (!inside(repoRoot, parent)) continue;
      stat = lstatSync(absolute);
      if (!stat.isSymbolicLink() && (!stat.isFile() || !inside(repoRoot, realpathSync(absolute)))) continue;
      if (stat.isFile() && !textCanContainReferences(readFileSync(absolute))) continue;
    } catch {
      continue;
    }
    const path = relative(repoRoot, absolute);
    if (safeEvidencePath(path)) return path;
  }
  return null;
}

function resolveGuidanceSymlinkTarget(repoRoot: string, sourcePath: string, linkTarget: string): string | null {
  const absolute = isAbsolute(linkTarget) ? resolve(linkTarget) : resolve(repoRoot, dirname(sourcePath), linkTarget);
  if (!inside(repoRoot, absolute) || !entryExists(absolute)) return null;
  try {
    if (!inside(repoRoot, realpathSync(dirname(absolute)))) return null;
    const stat = lstatSync(absolute);
    if (!stat.isSymbolicLink() && (!stat.isFile() || !inside(repoRoot, realpathSync(absolute)))) return null;
    if (stat.isFile() && !textCanContainReferences(readFileSync(absolute))) return null;
  } catch {
    return null;
  }
  const path = relative(repoRoot, absolute);
  return safeEvidencePath(path) ? path : null;
}

function liveGuidanceEvidence(repoRoot: string, path: string): LiveGuidanceEvidence {
  const absolute = join(repoRoot, path);
  const stat = lstatSync(absolute);
  const mode = permissionMode(stat.mode);
  if (stat.isSymbolicLink()) return { path, type: "symlink", mode, linkTarget: readlinkSync(absolute) };
  if (!stat.isFile()) throw new Error(`guidance must be a regular file or symlink: ${path}`);
  const bytes = readFileSync(absolute);
  if (!textCanContainReferences(bytes)) throw new Error(`guidance must be plain text: ${path}`);
  return { path, type: "file", mode, bytes };
}

function discoverGuidance(repo: string): LiveGuidanceEvidence[] {
  const root = repositoryRoot(repo);
  const all = findAgentEntryPaths(root);
  const entryPaths = new Set<string>();
  for (const path of all) {
    if (!AGENT_ENTRY_NAMES.has(basename(path)) || !safeEvidencePath(path)) continue;
    const absolute = join(root, path);
    if (entryExists(absolute) && isLegacyEntry(absolute)) entryPaths.add(path);
  }
  for (const path of MANAGED_ENTRY_PATHS) {
    if (!AGENT_ENTRY_NAMES.has(basename(path))) continue;
    const absolute = join(root, path);
    if (entryExists(absolute) && isLegacyEntry(absolute)) entryPaths.add(path);
  }

  const evidence = new Set([...entryPaths].filter((path) => !MANAGED_ENTRY_PATHS.includes(path)));
  const queue = [...entryPaths];
  const queued = new Set(queue);
  const reviewed = new Set<string>();
  while (queue.length) {
    const sourcePath = queue.shift()!;
    if (reviewed.has(sourcePath)) continue;
    reviewed.add(sourcePath);
    const absolute = join(root, sourcePath);
    const stat = lstatSync(absolute);
    if (stat.isSymbolicLink()) {
      const target = resolveGuidanceSymlinkTarget(root, sourcePath, readlinkSync(absolute));
      if (!target) throw new Error(`guidance symlink cannot be resolved to a safe in-repo text file: ${sourcePath}`);
      if (!MANAGED_ENTRY_PATHS.includes(target)) evidence.add(target);
      if (!reviewed.has(target) && !queued.has(target)) {
        queue.push(target);
        queued.add(target);
      }
      continue;
    }
    if (!stat.isFile()) continue;
    const bytes = readFileSync(absolute);
    if (!textCanContainReferences(bytes)) continue;
    for (const reference of explicitReferences(bytes.toString("utf8"))) {
      const target = resolveGuidanceReference(root, sourcePath, reference);
      if (!target) throw new Error(`cannot safely resolve referenced guidance ${reference} from ${sourcePath}`);
      if (!MANAGED_ENTRY_PATHS.includes(target)) evidence.add(target);
      if (!reviewed.has(target) && !queued.has(target)) {
        queue.push(target);
        queued.add(target);
      }
    }
  }
  return [...evidence].sort().map((path) => liveGuidanceEvidence(root, path));
}

export interface CaptureLegacyTestHooks {
  /** Deterministic seam for a concurrent index/snapshot change after install. */
  afterSnapshotsInstalled?: () => void;
}

export function captureLegacyEntries(repo: string, testHooks: CaptureLegacyTestHooks = {}): AdoptionIndex {
  const repoRoot = repositoryRoot(repo);
  const previousSource = readAdoptionIndexSource(repoRoot);
  const previous = previousSource.index;
  if (previous) {
    const mismatch = previous.entries.find((entry) => !verifyAdoptionEntry(repoRoot, entry));
    if (mismatch) throw new Error(`已有 legacy snapshot 与当前 ${mismatch.path} 不匹配；先审查变化，不能覆盖原始证据`);
  }
  const byPath = new Map((previous?.entries ?? []).map((entry) => [entry.path, entry]));
  const pendingSnapshots: PendingSnapshot[] = [];
  for (const path of MANAGED_ENTRY_PATHS) {
    if (byPath.has(path)) continue;
    const captured = captureEntry(repoRoot, path);
    if (captured.entry) byPath.set(path, captured.entry);
    if (captured.pendingSnapshot) pendingSnapshots.push(captured.pendingSnapshot);
  }
  const index: AdoptionIndex = {
    schema: "ai-harness/adoption/v1",
    capturedAt: previous?.capturedAt ?? new Date().toISOString(),
    entries: [...byPath.values()],
  };
  const indexContent = JSON.stringify(index, null, 2) + "\n";
  const installed = installPendingSnapshots(repoRoot, pendingSnapshots);
  try {
    testHooks.afterSnapshotsInstalled?.();
    writeManagedFiles(repoRoot, [[INDEX_REL, indexContent]], {
      authorize: (inspections) => {
        const current = inspections[0];
        if (!current) throw new Error("legacy adoption index preflight is missing");
        if (previousSource.raw === null) {
          if (current.kind !== "missing") throw new Error("legacy adoption index appeared during capture");
        } else if (current.kind !== "regular" || current.currentContent !== previousSource.raw) {
          throw new Error("legacy adoption index changed during capture");
        }
      },
    });
    return index;
  } catch (error) {
    throw new Error(`${errorMessage(error)}${retainedSnapshotNotice(installed)}`);
  }
}

export function adoptionAllows(repo: string, path: string): boolean {
  const entry = readAdoptionIndex(repo)?.entries.find((item) => item.path === path);
  return !!entry && verifyAdoptionEntry(repo, entry);
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function inside(root: string, candidate: string): boolean {
  const rel = relative(root, candidate);
  return rel === "" || (rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel));
}

function repositoryRoot(repo: string): string {
  let root: string;
  try {
    root = realpathSync(repo);
  } catch (error) {
    throw new Error(`cannot resolve repository root ${repo}: ${errorMessage(error)}`);
  }
  if (!statSync(root).isDirectory()) throw new Error(`repository root is not a directory: ${repo}`);
  return root;
}

function canonicalJson(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map((item) => canonicalJson(item)).join(",")}]`;
  const record = value as Record<string, unknown>;
  return `{${Object.keys(record)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonicalJson(record[key])}`)
    .join(",")}}`;
}

function candidateDigest(metadata: Omit<AdoptionCandidateMetadata, "candidateHash">): string {
  return sha256(canonicalJson(metadata));
}

function isSha256(value: unknown): value is string {
  return typeof value === "string" && /^[a-f0-9]{64}$/.test(value);
}

function safeRelativePath(path: string, label: string): string {
  if (!path || path.includes("\0") || isAbsolute(path)) throw new Error(`${label} path is unsafe: ${path}`);
  const normalized = normalize(path);
  if (normalized === "." || normalized === ".." || normalized.startsWith(`..${sep}`))
    throw new Error(`${label} path escapes its bundle: ${path}`);
  return normalized;
}

function existingAncestor(path: string): { ancestor: string; suffix: string[] } {
  const suffix: string[] = [];
  let cursor = path;
  while (!existsSync(cursor)) {
    const parent = dirname(cursor);
    if (parent === cursor) throw new Error(`cannot resolve destination parent: ${path}`);
    suffix.unshift(cursor.slice(parent.length + (parent.endsWith(sep) ? 0 : 1)));
    cursor = parent;
  }
  return { ancestor: cursor, suffix };
}

function prospectiveRealPath(path: string): string {
  const { ancestor, suffix } = existingAncestor(path);
  const stat = lstatSync(ancestor);
  if (!stat.isDirectory() && !stat.isSymbolicLink()) throw new Error(`destination parent is not a directory: ${ancestor}`);
  const resolvedAncestor = realpathSync(ancestor);
  if (!statSync(resolvedAncestor).isDirectory()) throw new Error(`destination parent is not a directory: ${ancestor}`);
  return resolve(resolvedAncestor, ...suffix);
}

function assertExternalPath(repoRoot: string, requestedPath: string, label: string): string {
  const absolute = resolve(requestedPath);
  const resolved = existsSync(absolute) ? realpathSync(absolute) : prospectiveRealPath(absolute);
  if (inside(repoRoot, resolved)) throw new Error(`${label} must be outside the repository: ${absolute}`);
  return resolved;
}

function prepareEmptyExternalDirectory(repoRoot: string, outputDir: string): string {
  const absolute = resolve(outputDir);
  if (existsSync(absolute)) {
    const stat = lstatSync(absolute);
    if (stat.isSymbolicLink()) throw new Error(`candidate output must not be a symlink: ${absolute}`);
    if (!stat.isDirectory()) throw new Error(`candidate output must be a directory: ${absolute}`);
    if (readdirSync(absolute).length > 0) throw new Error(`candidate output must be empty: ${absolute}`);
  }
  const expected = assertExternalPath(repoRoot, absolute, "candidate output");
  if (!existsSync(absolute)) mkdirSync(absolute, { recursive: true, mode: 0o700 });
  const stat = lstatSync(absolute);
  if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error(`candidate output is unsafe: ${absolute}`);
  const actual = realpathSync(absolute);
  if (actual !== expected || inside(repoRoot, actual)) throw new Error(`candidate output changed or escaped: ${absolute}`);
  chmodSync(actual, 0o700);
  return actual;
}

function ensurePrivateDirectory(bundleRoot: string, directory: string): void {
  const rel = relative(bundleRoot, directory);
  if (rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel)) throw new Error(`bundle directory escapes: ${directory}`);
  let cursor = bundleRoot;
  for (const component of rel.split(sep).filter(Boolean)) {
    cursor = join(cursor, component);
    if (!existsSync(cursor)) mkdirSync(cursor, { mode: 0o700 });
    const stat = lstatSync(cursor);
    if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error(`bundle directory is unsafe: ${cursor}`);
    chmodSync(cursor, 0o700);
  }
}

function bundleFilePath(bundleRoot: string, relativePath: string): string {
  const normalized = safeRelativePath(relativePath, "bundle artifact");
  const absolute = resolve(bundleRoot, normalized);
  if (!inside(bundleRoot, absolute) || absolute === bundleRoot) throw new Error(`bundle artifact escapes: ${relativePath}`);
  return absolute;
}

function privateWriteBundleFile(bundleRoot: string, relativePath: string, content: string | Buffer): string {
  const absolute = bundleFilePath(bundleRoot, relativePath);
  ensurePrivateDirectory(bundleRoot, dirname(absolute));
  writeFileSync(absolute, content, { flag: "wx", mode: 0o600 });
  chmodSync(absolute, 0o600);
  return absolute;
}

function readRegularFile(path: string, label: string): Buffer {
  let stat;
  try {
    stat = lstatSync(path);
  } catch (error) {
    throw new Error(`${label} is missing or unreadable at ${path}: ${errorMessage(error)}`);
  }
  if (stat.isSymbolicLink() || !stat.isFile()) throw new Error(`${label} must be a regular file: ${path}`);
  const fd = openSync(path, constants.O_RDONLY | constants.O_NOFOLLOW);
  try {
    if (!fstatSync(fd).isFile()) throw new Error(`${label} must be a regular file: ${path}`);
    return readFileSync(fd);
  } finally {
    closeSync(fd);
  }
}

function readBundleFile(bundleRoot: string, relativePath: string, label: string): Buffer {
  const absolute = bundleFilePath(bundleRoot, relativePath);
  const parentRel = relative(bundleRoot, dirname(absolute));
  let cursor = bundleRoot;
  for (const component of parentRel.split(sep).filter(Boolean)) {
    cursor = join(cursor, component);
    const stat = lstatSync(cursor);
    if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error(`${label} parent is unsafe: ${cursor}`);
  }
  return readRegularFile(absolute, label);
}

function parseJsonRecord(bytes: Buffer, label: string): Record<string, unknown> {
  let value: unknown;
  try {
    value = JSON.parse(bytes.toString("utf8"));
  } catch (error) {
    throw new Error(`${label} JSON is invalid: ${errorMessage(error)}`);
  }
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be a JSON object`);
  return value as Record<string, unknown>;
}

function readLiveIndexBytes(repoRoot: string): Buffer {
  const bytes = readRegularFile(join(repoRoot, INDEX_REL), "legacy adoption index");
  // Reuse the v1 parser so candidate authorization inherits the same path and
  // snapshot constraints as the existing exact-snapshot adoption mechanism.
  if (!readAdoptionIndex(repoRoot)) throw new Error(`${INDEX_REL} is required before preparing an adoption candidate`);
  return bytes;
}

function legacyEvidenceArtifact(entry: AdoptionEntry): string {
  return entry.type === "file"
    ? join("legacy", snapshotName(entry.path))
    : join("legacy", `${sha256(entry.path)}.symlink.json`);
}

function guidanceEvidenceArtifact(evidence: LiveGuidanceEvidence): string {
  return join("guidance", `${sha256(evidence.path)}.${evidence.type === "file" ? "document" : "symlink.json"}`);
}

function guidanceEvidenceBytes(evidence: LiveGuidanceEvidence): Buffer {
  if (evidence.type === "file") return evidence.bytes!;
  return Buffer.from(
    canonicalJson({ path: evidence.path, type: evidence.type, mode: evidence.mode, linkTarget: evidence.linkTarget }) + "\n",
  );
}

function expectedCandidateHash(metadata: AdoptionCandidateMetadata): string {
  const { candidateHash: _candidateHash, ...unsigned } = metadata;
  return candidateDigest(unsigned);
}

function validateCandidateMetadata(value: Record<string, unknown>): AdoptionCandidateMetadata {
  if (
    value.schema !== ADOPTION_CANDIDATE_SCHEMA ||
    value.assurance !== "declared" ||
    value.independence !== "unverified" ||
    !isSha256(value.candidateHash) ||
    !value.source ||
    typeof value.source !== "object" ||
    Array.isArray(value.source) ||
    !Array.isArray(value.legacy) ||
    !Array.isArray(value.guidance) ||
    !Array.isArray(value.targets)
  ) {
    throw new Error(`${CANDIDATE_METADATA} format is invalid`);
  }
  const source = value.source as Record<string, unknown>;
  const manifest = source.manifest as Record<string, unknown> | undefined;
  const legacyIndex = source.legacyIndex as Record<string, unknown> | undefined;
  if (
    !manifest ||
    manifest.path !== MANIFEST_REL ||
    typeof manifest.artifact !== "string" ||
    !isSha256(manifest.sha256) ||
    !legacyIndex ||
    legacyIndex.path !== INDEX_REL ||
    typeof legacyIndex.artifact !== "string" ||
    !isSha256(legacyIndex.sha256)
  ) {
    throw new Error(`${CANDIDATE_METADATA} source metadata is invalid`);
  }

  const legacyPaths = new Set<string>();
  for (const raw of value.legacy) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error(`${CANDIDATE_METADATA} legacy metadata is invalid`);
    const item = raw as Record<string, unknown>;
    if (
      typeof item.path !== "string" ||
      !MANAGED_ENTRY_PATHS.includes(item.path) ||
      legacyPaths.has(item.path) ||
      (item.type !== "file" && item.type !== "symlink") ||
      typeof item.artifact !== "string" ||
      !isSha256(item.sha256)
    ) {
      throw new Error(`${CANDIDATE_METADATA} legacy metadata is invalid`);
    }
    legacyPaths.add(item.path);
    if (item.type === "file" && (!isSha256(item.sourceSha256) || !validPermissionMode(item.mode)))
      throw new Error(`${CANDIDATE_METADATA} legacy file hash is invalid: ${item.path}`);
    if (item.type === "symlink" && typeof item.linkTarget !== "string")
      throw new Error(`${CANDIDATE_METADATA} legacy link evidence is invalid: ${item.path}`);
  }

  const guidancePaths = new Set<string>();
  for (const raw of value.guidance) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error(`${CANDIDATE_METADATA} guidance metadata is invalid`);
    const item = raw as Record<string, unknown>;
    if (
      typeof item.path !== "string" ||
      !safeEvidencePath(item.path) ||
      MANAGED_ENTRY_PATHS.includes(item.path) ||
      guidancePaths.has(item.path) ||
      (item.type !== "file" && item.type !== "symlink") ||
      typeof item.artifact !== "string" ||
      !isSha256(item.sha256) ||
      !validPermissionMode(item.mode)
    ) {
      throw new Error(`${CANDIDATE_METADATA} guidance metadata is invalid`);
    }
    guidancePaths.add(item.path);
    if (item.type === "symlink" && typeof item.linkTarget !== "string")
      throw new Error(`${CANDIDATE_METADATA} guidance symlink evidence is invalid: ${item.path}`);
  }

  const targetPaths = new Set<string>();
  for (const raw of value.targets) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error(`${CANDIDATE_METADATA} target metadata is invalid`);
    const item = raw as Record<string, unknown>;
    if (
      typeof item.path !== "string" ||
      typeof item.artifact !== "string" ||
      !isSha256(item.sha256) ||
      targetPaths.has(item.path)
    ) {
      throw new Error(`${CANDIDATE_METADATA} target metadata is invalid`);
    }
    safeRelativePath(item.path, "generated target");
    targetPaths.add(item.path);
  }

  safeRelativePath(manifest.artifact, "manifest artifact");
  safeRelativePath(legacyIndex.artifact, "legacy index artifact");
  for (const raw of value.legacy as Array<Record<string, unknown>>) safeRelativePath(raw.artifact as string, "legacy artifact");
  for (const raw of value.guidance as Array<Record<string, unknown>>) safeRelativePath(raw.artifact as string, "guidance artifact");
  for (const raw of value.targets as Array<Record<string, unknown>>) safeRelativePath(raw.artifact as string, "generated artifact");

  const metadata = value as unknown as AdoptionCandidateMetadata;
  if (expectedCandidateHash(metadata) !== metadata.candidateHash)
    throw new Error(`${CANDIDATE_METADATA} hash mismatch: ${metadata.candidateHash}`);
  return metadata;
}

function readCandidateBundle(repoRoot: string, candidateDir: string): { root: string; metadata: AdoptionCandidateMetadata } {
  const requested = resolve(candidateDir);
  if (!existsSync(requested)) throw new Error(`candidate bundle is missing: ${requested}`);
  const stat = lstatSync(requested);
  if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error(`candidate bundle must be a regular directory: ${requested}`);
  const root = realpathSync(requested);
  if (inside(repoRoot, root)) throw new Error(`candidate bundle must be outside the repository: ${requested}`);
  const metadata = validateCandidateMetadata(parseJsonRecord(readBundleFile(root, CANDIDATE_METADATA, "candidate metadata"), "candidate metadata"));

  const artifacts = [
    { path: metadata.source.manifest.artifact, hash: metadata.source.manifest.sha256, label: "candidate manifest" },
    { path: metadata.source.legacyIndex.artifact, hash: metadata.source.legacyIndex.sha256, label: "candidate legacy index" },
    ...metadata.legacy.map((item) => ({ path: item.artifact, hash: item.sha256, label: `legacy evidence ${item.path}` })),
    ...metadata.guidance.map((item) => ({ path: item.artifact, hash: item.sha256, label: `guidance evidence ${item.path}` })),
    ...metadata.targets.map((item) => ({ path: item.artifact, hash: item.sha256, label: `generated candidate ${item.path}` })),
  ];
  const artifactPaths = new Set<string>();
  for (const artifact of artifacts) {
    const normalized = safeRelativePath(artifact.path, artifact.label);
    if (artifactPaths.has(normalized)) throw new Error(`candidate artifact path is duplicated: ${normalized}`);
    artifactPaths.add(normalized);
    if (sha256(readBundleFile(root, normalized, artifact.label)) !== artifact.hash)
      throw new Error(`${artifact.label} hash mismatch at ${normalized}`);
  }
  return { root, metadata };
}

/**
 * Materialize a private, read-only-by-convention audit bundle outside the
 * repository. This never writes a managed target in the live repository.
 */
export function prepareAdoptionCandidate(repo: string, outputDir: string): AdoptionCandidateMetadata {
  const repoRoot = repositoryRoot(repo);
  const manifest = loadManifest(repoRoot);
  const errors = validateManifest(manifest).filter((issue) => issue.level === "error");
  if (errors.length) throw new Error(`manifest invalid: ${errors.map((issue) => issue.msg).join("; ")}`);
  const index = readAdoptionIndex(repoRoot);
  if (!index) throw new Error(`${INDEX_REL} is required before preparing an adoption candidate`);
  const invalidLegacy = index.entries.find((entry) => !verifyAdoptionEntry(repoRoot, entry));
  if (invalidLegacy) throw new Error(`legacy evidence is stale for ${invalidLegacy.path}; prepare refused`);
  const liveGuidance = discoverGuidance(repoRoot);

  const root = prepareEmptyExternalDirectory(repoRoot, outputDir);
  const manifestBytes = readRegularFile(join(repoRoot, MANIFEST_REL), "manifest");
  const indexBytes = readLiveIndexBytes(repoRoot);
  const manifestArtifact = join("source", "manifest.yaml");
  const indexArtifact = join("source", "legacy-index.json");
  privateWriteBundleFile(root, manifestArtifact, manifestBytes);
  privateWriteBundleFile(root, indexArtifact, indexBytes);

  const legacy: AdoptionCandidateLegacyEvidence[] = [];
  for (const entry of index.entries) {
    const artifact = legacyEvidenceArtifact(entry);
    if (entry.type === "file") {
      const snapshot = readRegularFile(join(repoRoot, entry.snapshot!), `legacy snapshot ${entry.path}`);
      privateWriteBundleFile(root, artifact, snapshot);
      legacy.push({
        path: entry.path,
        type: "file",
        artifact,
        sha256: sha256(snapshot),
        mode: entry.mode!,
        sourceSha256: entry.sha256!,
      });
    } else {
      const evidence = Buffer.from(canonicalJson({ path: entry.path, linkTarget: entry.linkTarget }) + "\n");
      privateWriteBundleFile(root, artifact, evidence);
      legacy.push({
        path: entry.path,
        type: "symlink",
        artifact,
        sha256: sha256(evidence),
        linkTarget: entry.linkTarget!,
      });
    }
  }

  const guidance: AdoptionCandidateGuidanceEvidence[] = [];
  for (const evidence of liveGuidance) {
    const artifact = guidanceEvidenceArtifact(evidence);
    const bytes = guidanceEvidenceBytes(evidence);
    privateWriteBundleFile(root, artifact, bytes);
    guidance.push({
      path: evidence.path,
      type: evidence.type,
      artifact,
      sha256: sha256(bytes),
      mode: evidence.mode,
      ...(evidence.type === "symlink" ? { linkTarget: evidence.linkTarget! } : {}),
    });
  }

  const targets: AdoptionCandidateTarget[] = [];
  for (const [path, content] of renderTargets(manifest)) {
    const artifact = join("generated", path);
    const bytes = Buffer.from(content, "utf8");
    privateWriteBundleFile(root, artifact, bytes);
    targets.push({ path, artifact, sha256: sha256(bytes) });
  }

  const unsigned: Omit<AdoptionCandidateMetadata, "candidateHash"> = {
    schema: ADOPTION_CANDIDATE_SCHEMA,
    assurance: "declared",
    independence: "unverified",
    source: {
      manifest: { path: MANIFEST_REL, artifact: manifestArtifact, sha256: sha256(manifestBytes) },
      legacyIndex: { path: INDEX_REL, artifact: indexArtifact, sha256: sha256(indexBytes) },
    },
    legacy,
    guidance,
    targets,
  };
  const metadata: AdoptionCandidateMetadata = { ...unsigned, candidateHash: candidateDigest(unsigned) };
  privateWriteBundleFile(root, CANDIDATE_METADATA, canonicalJson(metadata) + "\n");
  return metadata;
}

function externalReceiptPath(repoRoot: string, candidateRoot: string, requested?: string): string {
  const absolute = resolve(requested ?? join(candidateRoot, RECEIPT_DEFAULT));
  const parent = dirname(absolute);
  if (!existsSync(parent)) throw new Error(`receipt parent must already exist: ${parent}`);
  const parentStat = lstatSync(parent);
  if (parentStat.isSymbolicLink() || !parentStat.isDirectory()) throw new Error(`receipt parent is unsafe: ${parent}`);
  const resolvedParent = realpathSync(parent);
  const resolved = join(resolvedParent, relative(parent, absolute));
  if (inside(repoRoot, resolved)) throw new Error(`receipt must be outside the repository: ${absolute}`);
  if (existsSync(absolute)) throw new Error(`receipt already exists: ${absolute}`);
  return resolved;
}

/** Record only a declared reviewer verdict; this deliberately makes no claim of semantic validation or reviewer independence. */
export function recordAdoptionAudit(
  repo: string,
  candidateDir: string,
  options: RecordAdoptionAuditOptions,
): RecordedAdoptionAudit {
  const repoRoot = repositoryRoot(repo);
  if (options.verdict !== "pass" && options.verdict !== "fail") throw new Error("audit verdict must be pass or fail");
  const reason = options.reason?.trim();
  if (!reason) throw new Error("audit reason must not be empty");
  const candidate = readCandidateBundle(repoRoot, candidateDir);
  const reportRequested = resolve(options.reportPath);
  const reportBytes = readRegularFile(reportRequested, "audit report");
  const reportPath = realpathSync(reportRequested);
  const receiptPath = externalReceiptPath(repoRoot, candidate.root, options.receiptPath);
  const receipt: AdoptionAuditReceipt = {
    schema: ADOPTION_RECEIPT_SCHEMA,
    candidateHash: candidate.metadata.candidateHash,
    candidatePath: candidate.root,
    verdict: options.verdict,
    reason,
    report: { path: reportPath, sha256: sha256(reportBytes) },
    recordedAt: new Date().toISOString(),
    assurance: "declared",
    independence: "unverified",
  };
  writeFileSync(receiptPath, canonicalJson(receipt) + "\n", { flag: "wx", mode: 0o600 });
  chmodSync(receiptPath, 0o600);
  return { receipt, receiptPath };
}

function readReceipt(repoRoot: string, receiptPath: string): AdoptionAuditReceipt {
  const requested = resolve(receiptPath);
  const resolved = assertExternalPath(repoRoot, requested, "receipt");
  if (resolved !== realpathSync(requested)) throw new Error(`receipt path changed: ${requested}`);
  const value = parseJsonRecord(readRegularFile(requested, "adoption audit receipt"), "adoption audit receipt");
  if (
    value.schema !== ADOPTION_RECEIPT_SCHEMA ||
    !isSha256(value.candidateHash) ||
    typeof value.candidatePath !== "string" ||
    (value.verdict !== "pass" && value.verdict !== "fail") ||
    typeof value.reason !== "string" ||
    !value.reason.trim() ||
    typeof value.recordedAt !== "string" ||
    value.assurance !== "declared" ||
    value.independence !== "unverified" ||
    !value.report ||
    typeof value.report !== "object" ||
    Array.isArray(value.report)
  ) {
    throw new Error(`adoption audit receipt format is invalid: ${requested}`);
  }
  const report = value.report as Record<string, unknown>;
  if (typeof report.path !== "string" || !isAbsolute(report.path) || !isSha256(report.sha256))
    throw new Error(`adoption audit receipt report binding is invalid: ${requested}`);
  return value as unknown as AdoptionAuditReceipt;
}

function samePathList(left: readonly string[], right: readonly string[]): boolean {
  return left.length === right.length && left.every((path, index) => path === right[index]);
}

/**
 * Authorize first takeover on the exact managed-file preflight used by the
 * transaction. All evidence is content-bound; a pass receipt is declared and
 * independence remains explicitly unverified.
 */
export function assertManagedFileAdoptionReceipt(
  repo: string,
  inspections: readonly ManagedFileInspection[],
  candidateDir: string,
  receiptPath: string,
): void {
  const unmanaged = inspections.filter(
    (inspection) =>
      inspection.kind === "regular" &&
      !inspection.satisfiesDesired &&
      !inspection.currentContent?.startsWith(GENERATED_MARKER),
  );
  if (!unmanaged.length) return;

  const repoRoot = repositoryRoot(repo);
  const unproven = unmanaged.filter((inspection) => !adoptionAllows(repoRoot, inspection.relativePath));
  if (unproven.length)
    throw new Error(`legacy snapshot is missing, stale, or changed for: ${unproven.map((item) => item.relativePath).join(", ")}`);

  const index = readAdoptionIndex(repoRoot);
  if (!index) throw new Error(`${INDEX_REL} is required for adoption authorization`);
  const invalidLegacy = index.entries.find((entry) => !verifyAdoptionEntry(repoRoot, entry));
  if (invalidLegacy) throw new Error(`live legacy evidence changed for ${invalidLegacy.path}`);
  const liveIndexBytes = readLiveIndexBytes(repoRoot);
  const candidate = readCandidateBundle(repoRoot, candidateDir);
  const metadata = candidate.metadata;

  if (metadata.source.legacyIndex.sha256 !== sha256(liveIndexBytes)) throw new Error("legacy adoption index changed after candidate preparation");
  if (sha256(readBundleFile(candidate.root, metadata.source.legacyIndex.artifact, "candidate legacy index")) !== sha256(liveIndexBytes))
    throw new Error("candidate legacy index no longer matches the live index");

  if (!samePathList(metadata.legacy.map((item) => item.path), index.entries.map((entry) => entry.path)))
    throw new Error("candidate legacy evidence does not match the live index");
  for (let i = 0; i < index.entries.length; i++) {
    const entry = index.entries[i];
    const evidence = metadata.legacy[i];
    if (entry.type !== evidence.type) throw new Error(`candidate legacy type changed for ${entry.path}`);
    const artifact = readBundleFile(candidate.root, evidence.artifact, `legacy evidence ${entry.path}`);
    if (entry.type === "file") {
      const liveSnapshot = readRegularFile(join(repoRoot, entry.snapshot!), `legacy snapshot ${entry.path}`);
      if (evidence.sourceSha256 !== entry.sha256 || evidence.mode !== entry.mode || !artifact.equals(liveSnapshot))
        throw new Error(`candidate legacy bytes or mode changed for ${entry.path}`);
    } else {
      const expected = Buffer.from(canonicalJson({ path: entry.path, linkTarget: entry.linkTarget }) + "\n");
      if (evidence.linkTarget !== entry.linkTarget || !artifact.equals(expected))
        throw new Error(`candidate legacy link evidence changed for ${entry.path}`);
    }
  }

  const liveGuidance = discoverGuidance(repoRoot);
  if (!samePathList(metadata.guidance.map((item) => item.path), liveGuidance.map((item) => item.path)))
    throw new Error("live guidance inventory changed after candidate preparation");
  for (let i = 0; i < liveGuidance.length; i++) {
    const live = liveGuidance[i];
    const evidence = metadata.guidance[i];
    if (
      evidence.type !== live.type ||
      evidence.mode !== live.mode ||
      (live.type === "symlink" && evidence.linkTarget !== live.linkTarget)
    )
      throw new Error(`live guidance topology or mode changed for ${live.path}`);
    const artifact = readBundleFile(candidate.root, evidence.artifact, `guidance evidence ${live.path}`);
    if (!artifact.equals(guidanceEvidenceBytes(live))) throw new Error(`live guidance bytes changed for ${live.path}`);
  }

  const receipt = readReceipt(repoRoot, receiptPath);
  if (receipt.candidatePath !== candidate.root || receipt.candidateHash !== metadata.candidateHash)
    throw new Error(`receipt does not bind candidate ${metadata.candidateHash}`);
  if (receipt.verdict !== "pass") throw new Error(`adoption audit verdict is ${receipt.verdict}; pass is required`);
  const reportPath = resolve(receipt.report.path);
  if (realpathSync(reportPath) !== receipt.report.path) throw new Error(`audit report path changed: ${reportPath}`);
  if (sha256(readRegularFile(reportPath, "audit report")) !== receipt.report.sha256)
    throw new Error(`audit report hash mismatch: ${receipt.report.sha256}`);

  const manifestBytes = readRegularFile(join(repoRoot, MANIFEST_REL), "manifest");
  if (metadata.source.manifest.sha256 !== sha256(manifestBytes)) throw new Error("manifest changed after candidate preparation");
  if (!readBundleFile(candidate.root, metadata.source.manifest.artifact, "candidate manifest").equals(manifestBytes))
    throw new Error("candidate manifest no longer matches the live manifest");
  const manifest = loadManifest(repoRoot);
  const errors = validateManifest(manifest).filter((issue) => issue.level === "error");
  if (errors.length) throw new Error(`manifest invalid: ${errors.map((issue) => issue.msg).join("; ")}`);
  const rendered = renderTargets(manifest);
  if (!samePathList(metadata.targets.map((target) => target.path), rendered.map(([path]) => path)))
    throw new Error("current render target list differs from the audited candidate");
  if (!samePathList(inspections.map((inspection) => inspection.relativePath), rendered.map(([path]) => path)))
    throw new Error("managed-file preflight does not match the audited render target list");
  for (let i = 0; i < rendered.length; i++) {
    const [path, content] = rendered[i];
    const candidateTarget = metadata.targets[i];
    const candidateBytes = readBundleFile(candidate.root, candidateTarget.artifact, `generated candidate ${path}`);
    if (!candidateBytes.equals(Buffer.from(content, "utf8"))) throw new Error(`current render differs from audited candidate: ${path}`);
  }
}

/** Refuse unmanaged takeover unless the caller used the candidate + receipt API above. */
export function assertManagedFileAdoption(
  _repo: string,
  inspections: readonly ManagedFileInspection[],
  adoptExisting: boolean,
): void {
  const unmanaged = inspections.filter(
    (inspection) =>
      inspection.kind === "regular" &&
      !inspection.satisfiesDesired &&
      !inspection.currentContent?.startsWith(GENERATED_MARKER),
  );
  if (!unmanaged.length) return;
  const legacyFlag = adoptExisting ? "；legacy snapshot + --adopt-existing alone is not authorization" : "";
  throw new Error(
    `拒绝覆盖未由 harness-kit 管理的文件: ${unmanaged.map((item) => item.relativePath).join(", ")}${legacyFlag}；` +
      "先运行 prepare-adoption，在独立审查后记录 pass receipt，再把同一 candidate + audit receipt 交给 sync",
  );
}
