import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export function sha256(input: string | Buffer): string {
  return createHash("sha256").update(input).digest("hex");
}

export function hashFile(absPath: string): string | null {
  if (!existsSync(absPath)) return null;
  return sha256(readFileSync(absPath));
}

export function readText(absPath: string): string | null {
  return existsSync(absPath) ? readFileSync(absPath, "utf8") : null;
}

export function writeText(absPath: string, content: string): void {
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, content);
}

// ASCII-only status output (no emoji / box-drawing).
export const ok = (m: string) => console.log(`  OK   ${m}`);
export const err = (m: string) => console.log(`  ERR  ${m}`);
export const warn = (m: string) => console.log(`  WARN ${m}`);
export const info = (m: string) => console.log(m);

export const GEN_HEADER = (src = ".agents/manifest.yaml") =>
  `<!-- GENERATED by ai-harness — DO NOT EDIT. Source of truth: ${src}. Run \`mk-harness sync\` to regenerate. -->`;
